[package]
name = "fdk-mqa-scoring-service"
version = "0.1.0"
edition = "2021"

[dependencies]
avro-rs = "0.13.0"
diesel = { version = "2.0.0-rc.0", features = ["postgres", "r2d2"] }
diesel_migrations = { version = "2.0.0-rc.0", features = ["postgres"] }
futures = "0.3.21"
lazy_static = "1.4.0"
oxigraph = "0.3.1"
r2d2 = "0.8.9"
rand = "0.8.5"
rdkafka = "0.28.0"
regex = "1.5"
schema_registry_converter = { version = "2.1.0", features = ["avro", "blocking"] }
serde = "1.0.137"
serde_derive = "1.0.137"
thiserror = "1.0"
tokio = { version = "1.18.2", features = ["full"] }
uuid = { version = "1.0.0", features = ["v4"] }
