[package]
name = "fdk-mqa-scoring-service"
version = "0.1.0"
edition = "2021"
authors = ["Amund Tenstad <digdir@amund.io>"]

[dependencies]
oxigraph = "0.3.1"
regex = "1.5"
thiserror = "1.0"
rand = "0.8.5"
tokio = { version = "1.18.2", features = ["full"] }
avro-rs = "0.13.0"
rdkafka = "0.28.0"
futures = "0.3.21"
schema_registry_converter = { version = "2.1.0", features = ["avro", "blocking"] }
serde = "1.0.137"
serde_derive = "1.0.137"
