[package]
name = "fdk-mqa-scoring-service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1.0"
avro-rs = "0.13.0"
chrono = "0.4.19"
futures = "0.3.26"
httptest = "0.15.4"
lazy_static = "1.4.0"
oxigraph = "0.3.1"
prometheus = "0.13.1"
rand = "0.8.5"
rdkafka = "0.28.0"
regex = "1.5"
reqwest = "0.11.11"
schema_registry_converter = { version = "2.1.0", features = ["avro", "blocking"] }
serde = "1.0.141"
serde_derive = "1.0.141"
serde_json = "1.0.81"
sophia = "0.7.2"
sophia_jsonld = "0.7.2"
thiserror = "1.0"
tokio = { version = "1.18.2", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber =  { version = "0.3.11", features = ["json"] }
uuid = { version = "1.0.0", features = ["v4"] }
