[package]
name = "fdk-mqa-scoring-service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
apache-avro = "0.16.0"
chrono = "0.4.31"
futures = "0.3.29"
httptest = "0.15.5"
lazy_static = "1.4.0"
oxigraph = "0.3.20"
prometheus = "0.13.3"
rand = "0.8.5"
rdkafka = "0.36.0"
regex = "1.10.2"
reqwest = "0.11.22"
schema_registry_converter = { version = "4.0.0", features = ["avro", "blocking"] }
serde = "1.0.192"
serde_derive = "1.0.192"
serde_json = "1.0.108"
sophia = "0.7.2"
sophia_jsonld = "0.7.2"
thiserror = "1.0"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json", "env-filter", "tracing-log"] }
uuid = { version = "1.6.1", features = ["v4"] }
