apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-mqa-scoring-service
  labels:
    app: fdk-mqa-scoring-service
    fdk.service: fdk-mqa-scoring-service
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-mqa-scoring-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fdk-mqa-scoring-service
        fdk.service: fdk-mqa-scoring-service
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: fdk-mqa-scoring-service
          image: fdk-mqa-scoring-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: common
                  key: NAMESPACE
            - name: SCHEMA_REGISTRY
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality
                  key: SCHEMA_REGISTRY
            - name: BROKERS
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality
                  key: BROKERS
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality
                  key: API_KEY
            - name: SCORING_API_URL
              value: http://fdk-mqa-scoring-api:8082
          resources:
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "1Gi"
          livenessProbe:
            exec:
              command:
                - "true"
          readinessProbe:
            exec:
              command:
                - "true"
      restartPolicy: Always
