---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-fdk-mqa-scoring-service.yaml
  - deployment-fdk-mqa-scoring-service.yaml

images:
  - name: fdk-mqa-scoring-service
    newName: ghcr.io/informasjonsforvaltning/fdk-mqa-scoring-service
    newTag: $(GIT_COMMIT_SHA)
