---
apiVersion: v1
kind: Service
metadata:
  name: fdk-mqa-scoring-service
spec:
  selector:
    fdk.service: fdk-mqa-scoring-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8081
  type: NodePort
